spring:
  application:
    name: interest-fee-calculation
  datasource:
    url: jdbc:h2:mem:interestcalc;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  batch:
    job:
      enabled: false
